name: PyPI Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tag push (v0.0.1, v1.2.3, etc.)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract version from __init__.py
        id: extract_version
        run: |
          VERSION=$(python -c "from timod import __version__; print(__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Store version in environment variable

      - name: Show version
        run: echo "The version is $VERSION"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
        env:
          VERSION: ${{ env.VERSION }}  # Use the extracted version in the publish step

